"window.opacity" = 0.9

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x1D202F"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x1D202F"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xc0caf5"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window.padding]
x = 1
y = 0
